### ISSUE TITLE
GitHub links related to two papers

### ISSUE THREAD

**Issue by iwuqing** [xmindflow/Awesome-Implicit-Neural-Representations-in-Medical-imaging#1]
Hi Amirali!

I'm excited to share GitHub links related to two papers.

**Paper Title:** Self-Supervised Coordinate Projection Network for Sparse-View Computed Tomography.
**GitHub Link:** https://github.com/iwuqing/SCOPE

**Paper Title:** Neural Computed Tomography.
**GitHub Link:** https://github.com/KunalMGupta/DIFIR-CT

**Comment by amirhossein-kz** [comment]
Hi @iwuqing,
Thank you very much for your interest in our repo. It is now updated. Thanks!
